runtime: java21
env: flex
runtime_config:
  jdk: openjdk9
env_variables:
  SPRING_PROFILES_ACTIVE: "mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1